### ISSUE TITLE
CLI docs is not shown

### ISSUE THREAD

**Issue by mb-wali** [tu-graz-library/repository-cli#14]
* write documentation on how to build/run the docs locally. add the documentation in this issue.
* find out why the docs are not shown see screenshot:
![fix-docs](https://user-images.githubusercontent.com/44528277/116090077-c894b100-a6a3-11eb-8d8c-211cb81e5ef8.png)

**Comment by rekt-hard** [comment]
Generate documentation as .html files:
- cd into root directory of the repository
- install dependencies `pip install -e ".[all, postgresql, elasticsearch7]"`
- cd into docs folder `cd docs`
- build html files `make html`

Generated output files will be in the **_docs/\_build/html_** folder. Opening index.html in the browser will display the generated documentation
